# Generated by Django 4.2.5 on 2023-09-13 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expensesharesummary_total_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensesharesummary',
            old_name='total_paid',
            new_name='to_pay',
        ),
    ]
